In [1]:
import pandas as pd

In [2]:
file = "HDLT_Sports Shoes Take Home Assignment 2021.csv"

In [3]:
file_df = pd.read_csv(file)
file_df.head(5)

,Campaign Name,Ad Set Name,Ad Name,Day,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks,Status reasons
0,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_WhiteShoe,2020-12-06,34584,24.0,575.2901,14.0,24.0,194.0,active
1,Prospecting -- Signups and Purchases,US_Interest_Basketball,HDLT_Test_Animated_Basketball,2020-12-23,31495,23.0,494.6203,14.0,23.0,187.0,active
2,Prospecting -- Signups and Purchases,US_Interest_Basketball,HDLT_Test_Animated_Basketball,2020-12-25,32807,22.0,405.1159,9.0,22.0,184.0,active
3,Prospecting -- Signups and Purchases,US_Interest_Basketball,HDLT_Test_Animated_Basketball,2020-12-26,30201,23.0,402.2864,14.0,23.0,179.0,active
4,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_WhiteShoe,2020-12-07,31713,26.0,572.4368,10.0,26.0,178.0,limited by budget

In [4]:
file_df.dtypes

Campaign Name          object
Ad Set Name            object
Ad Name                object
Day                    object
Impressions             int64
Results               float64
Amount Spent (USD)    float64
Purchase              float64
Signup                float64
Link Clicks           float64
Status reasons         object
dtype: object

In [5]:
##Question 1

In [6]:
cost = file_df["Amount Spent (USD)"].sum()
clicks = file_df["Purchase"].sum()
cost_per_click = cost/clicks
cost_per_click

34.140708527131785

In [7]:
##Question 2

In [8]:
file_df.groupby("Ad Set Name").sum()

,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks
Ad Set Name,,,,,,
ALL_Retargeting_Signup No Purchase,7157,6758.0,263.1170,0.0,0.0,17.0
ALL_Retargeting_Site Visitors,260817,256792.0,270.9965,0.0,0.0,62.0
US_Interest_Basketball,287266,209.0,4384.5710,135.0,209.0,1598.0
US_Lookalike_RecentPurchases,399350,312.0,6277.1776,203.0,312.0,2331.0
WW_Interest_Cricket,6191,4.0,462.9274,0.0,4.0,31.0
WW_Lookalike_RecentPurchases,556830,520.0,10361.9675,307.0,520.0,3704.0

In [9]:
USA = file_df[(file_df["Ad Set Name"] == "US_Interest_Basketball") | (file_df["Ad Set Name"] == "US_Lookalike_RecentPurchases")]
USA["Purchase"].sum()

338.0

In [10]:
World_wide = file_df[(file_df["Ad Set Name"] == "WW_Lookalike_RecentPurchases") | (file_df["Ad Set Name"] == "WW_Interest_Cricket")]
World_wide["Purchase"].sum()

307.0

In [11]:
##Question 3

In [12]:
file_df.sort_values(by=["Day"]).head(5)

,Campaign Name,Ad Set Name,Ad Name,Day,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks,Status reasons
35,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_WhiteShoe,2020-12-01,17553,15.0,360.8472,9.0,15.0,87.0,campaign paused; limited by budget
107,Prospecting -- Signups and Purchases,WW_Interest_Cricket,HDLT_Test_Static_Cricket,2020-12-01,2162,1.0,199.5539,NaN,1.0,10.0,na
24,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Animated_ShoeSpin,2020-12-01,15456,9.0,269.0864,7.0,9.0,134.0,campaign paused; limited by budget
146,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_BlackShoe,2020-12-01,867,NaN,16.0217,NaN,NaN,2.0,indc
32,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Animated_ShoeSpin,2020-12-02,17348,14.0,263.4513,7.0,14.0,101.0,status check

In [13]:
file_df["Day"] = pd.to_datetime(file_df["Day"], format="%Y-%m-%d")
file_df.dtypes

Campaign Name                 object
Ad Set Name                   object
Ad Name                       object
Day                   datetime64[ns]
Impressions                    int64
Results                      float64
Amount Spent (USD)           float64
Purchase                     float64
Signup                       float64
Link Clicks                  float64
Status reasons                object
dtype: object

In [14]:
from datetime import date, timedelta

In [15]:
seven_days = file_df.loc[(file_df["Day"] >="2020-12-01")
                        & (file_df["Day"] < "2020-12-08")]
seven_days.sort_values(by=["Day"]).head(5)

,Campaign Name,Ad Set Name,Ad Name,Day,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks,Status reasons
24,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Animated_ShoeSpin,2020-12-01,15456,9.0,269.0864,7.0,9.0,134.0,campaign paused; limited by budget
35,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_WhiteShoe,2020-12-01,17553,15.0,360.8472,9.0,15.0,87.0,campaign paused; limited by budget
146,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_BlackShoe,2020-12-01,867,NaN,16.0217,NaN,NaN,2.0,indc
107,Prospecting -- Signups and Purchases,WW_Interest_Cricket,HDLT_Test_Static_Cricket,2020-12-01,2162,1.0,199.5539,NaN,1.0,10.0,na
141,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_BlackShoe,2020-12-02,504,NaN,8.3093,NaN,NaN,4.0,status check

In [16]:
Cost = seven_days["Amount Spent (USD)"].sum()
Cost

5187.355300000001

In [17]:
Impression = seven_days["Impressions"].sum()
Impression

270492

In [18]:
Cost_per_impression = Cost/Impression
Cost_per_impression

0.01917748140425595

In [19]:
CPM = Cost_per_impression*1000
CPM

19.17748140425595

In [20]:
##Question 4

In [21]:
Groups = file_df.groupby("Ad Set Name").sum()
Groups

,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks
Ad Set Name,,,,,,
ALL_Retargeting_Signup No Purchase,7157,6758.0,263.1170,0.0,0.0,17.0
ALL_Retargeting_Site Visitors,260817,256792.0,270.9965,0.0,0.0,62.0
US_Interest_Basketball,287266,209.0,4384.5710,135.0,209.0,1598.0
US_Lookalike_RecentPurchases,399350,312.0,6277.1776,203.0,312.0,2331.0
WW_Interest_Cricket,6191,4.0,462.9274,0.0,4.0,31.0
WW_Lookalike_RecentPurchases,556830,520.0,10361.9675,307.0,520.0,3704.0

In [22]:
CTR = Groups["Link Clicks"]/Groups["Impressions"]
CTR.sort_values()

Ad Set Name
ALL_Retargeting_Site Visitors         0.000238
ALL_Retargeting_Signup No Purchase    0.002375
WW_Interest_Cricket                   0.005007
US_Interest_Basketball                0.005563
US_Lookalike_RecentPurchases          0.005837
WW_Lookalike_RecentPurchases          0.006652
dtype: float64

In [23]:
CPP = Groups["Amount Spent (USD)"]/Groups["Purchase"]
CPP.sort_values()

Ad Set Name
US_Lookalike_RecentPurchases          30.922057
US_Interest_Basketball                32.478304
WW_Lookalike_RecentPurchases          33.752337
ALL_Retargeting_Signup No Purchase          inf
ALL_Retargeting_Site Visitors               inf
WW_Interest_Cricket                         inf
dtype: float64

In [24]:
##Question 6

In [25]:
##Question 7 Animated vs. Static
#Static
Ads_Static = file_df[(file_df["Ad Name"].str.contains("Static"))]
Ads_Static_Sum = Ads_Static["Amount Spent (USD)"].sum()/Ads_Static["Purchase"].sum()
Ads_Static_Sum

32.61017578947367

In [26]:
#Animated
Ads_Animated = file_df[(file_df["Ad Name"].str.contains("Animated"))]
Ads_Animated_Sum = Ads_Animated["Amount Spent (USD)"].sum()/Ads_Animated["Purchase"].sum()
Ads_Animated_Sum

33.86873166666667

In [27]:
file_df["CPP"] = file_df["Amount Spent (USD)"]/file_df["Purchase"]
file_df.head(5)

,Campaign Name,Ad Set Name,Ad Name,Day,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks,Status reasons,CPP
0,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_WhiteShoe,2020-12-06,34584,24.0,575.2901,14.0,24.0,194.0,active,41.092150
1,Prospecting -- Signups and Purchases,US_Interest_Basketball,HDLT_Test_Animated_Basketball,2020-12-23,31495,23.0,494.6203,14.0,23.0,187.0,active,35.330021
2,Prospecting -- Signups and Purchases,US_Interest_Basketball,HDLT_Test_Animated_Basketball,2020-12-25,32807,22.0,405.1159,9.0,22.0,184.0,active,45.012878
3,Prospecting -- Signups and Purchases,US_Interest_Basketball,HDLT_Test_Animated_Basketball,2020-12-26,30201,23.0,402.2864,14.0,23.0,179.0,active,28.734743
4,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_WhiteShoe,2020-12-07,31713,26.0,572.4368,10.0,26.0,178.0,limited by budget,57.243680

In [28]:
file_df.sort_values("CPP").head(5)

,Campaign Name,Ad Set Name,Ad Name,Day,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks,Status reasons,CPP
112,Prospecting -- Signups and Purchases,US_Lookalike_RecentPurchases,HDLT_Test_Static_BlackShoe,2020-12-14,412,1.0,5.5396,1.0,1.0,8.0,campaign paused; limited by budget,5.539600
132,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_BlackShoe,2020-12-26,375,1.0,7.5094,1.0,1.0,4.0,active,7.509400
153,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_BlackShoe,2020-12-28,351,NaN,8.1064,1.0,NaN,1.0,na,8.106400
137,Prospecting -- Signups and Purchases,WW_Lookalike_RecentPurchases,HDLT_Test_Static_BlackShoe,2020-12-27,358,1.0,8.1661,1.0,1.0,4.0,indc,8.166100
50,Prospecting -- Signups and Purchases,US_Lookalike_RecentPurchases,HDLT_Test_Static_WhiteShoe,2020-12-20,6053,4.0,77.9597,8.0,4.0,54.0,status check,9.744962

In [29]:
##Question 8 Day with the lowest cost per signup
Group_Day = file_df.groupby("Day").sum()
Group_Day.head(5)

,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks,CPP
Day,,,,,,,
2020-12-01,36038,25.0,845.5092,16.0,25.0,233.0,78.535048
2020-12-02,40586,38.0,743.5298,23.0,38.0,260.0,62.757162
2020-12-03,39206,45.0,741.0036,24.0,45.0,272.0,53.054784
2020-12-04,36032,31.0,719.2522,16.0,31.0,259.0,81.902132
2020-12-05,38978,50.0,731.6799,29.0,50.0,270.0,72.766900

In [30]:
Group_Day["CPS"] = Group_Day["Amount Spent (USD)"]/Group_Day["Signup"]
Group_Day.sort_values("CPS").head(5)

,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks,CPP,CPS
Day,,,,,,,,
2020-12-05,38978,50.0,731.6799,29.0,50.0,270.0,72.766900,14.633598
2020-12-19,37979,43.0,704.1805,27.0,43.0,274.0,134.061367,16.376291
2020-12-27,41129,41.0,674.4052,28.0,41.0,272.0,86.797314,16.448907
2020-12-03,39206,45.0,741.0036,24.0,45.0,272.0,53.054784,16.466747
2020-12-25,49076,40.0,690.7732,23.0,40.0,308.0,81.499553,17.269330

In [31]:
#Question 9

purchases_Lookalike = file_df[(file_df["Ad Set Name"].str.contains("Lookalike"))]
purchases_rate = purchases_Lookalike["Purchase"].sum()/purchases_Lookalike["Signup"].sum()
purchases_rate

0.6129807692307693

In [32]:
purchases_Interest = file_df[(file_df["Ad Set Name"].str.contains("Interest"))]
purchases_rate_2 = purchases_Interest["Purchase"].sum()/purchases_Interest["Signup"].sum()
purchases_rate_2

0.6338028169014085

In [33]:
#Question 10

In [34]:
Retarget_Campaign = file_df[(file_df["Ad Set Name"] == "ALL_Retargeting_Signup No Purchase")]
Retarget_Campaign

,Campaign Name,Ad Set Name,Ad Name,Day,Impressions,Results,Amount Spent (USD),Purchase,Signup,Link Clicks,Status reasons,CPP
118,Retargeting Test,ALL_Retargeting_Signup No Purchase,Retargeting Ad,2020-12-31,2808,2638.0,112.4984,NaN,NaN,6.0,active,NaN
122,Retargeting Test,ALL_Retargeting_Signup No Purchase,Retargeting Ad,2020-12-30,2639,2470.0,120.6047,NaN,NaN,6.0,na,NaN
128,Retargeting Test,ALL_Retargeting_Signup No Purchase,Retargeting Ad,2020-12-29,1710,1650.0,30.0139,NaN,NaN,5.0,na,NaN

In [35]:
Retarget_Camp_Cost = Retarget_Campaign["Amount Spent (USD)"].sum()/Retarget_Campaign["Link Clicks"].sum()
Retarget_Camp_Cost

15.477470588235292